Repository dandi/s3invsync, pull requests merged in 2025-01, with the labels that each got.

#113 Add docs for most items
  .github/workflows/test.yml
  src/consts.rs
  src/inventory/item.rs
  src/inventory/list.rs
  src/inventory/mod.rs
  src/keypath.rs
  src/manifest.rs
  src/s3/location.rs
  src/s3/mod.rs
  src/s3/streams.rs
  src/syncer.rs
  src/timestamps/date.rs
  src/timestamps/datehm.rs
  src/timestamps/maybe_hm.rs
  src/timestamps/mod.rs
  src/timestamps/util.rs
  src/util.rs
Labels: documentation, code quality

#114 v0.1.0-alpha.2 — Second alpha release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  LICENSE
Labels: release

#116 `build.yml`: Attach artifacts to releases as cargo-binstall-compatible zips
  .github/workflows/build.yml
Labels: CI

#119 Document program requirements for the inventory
  README.md
Labels: documentation

#121 Update lints for Rust 1.84
  Cargo.toml
Labels: upkeep

#120 Support all documented S3 Inventory fields in inventory lists
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  src/inventory/fields.rs
  src/inventory/item.rs
  src/inventory/list.rs
  src/inventory/mod.rs
  src/manifest.rs
  src/s3/mod.rs
  src/syncer.rs
Labels: enhancement, generalization

#123 Enhance installation instructions in README
  README.md
Labels: documentation

#124 Include README, license, and changelog in release assets
  .github/workflows/build.yml
Labels: CI

#126 Add codespell config, pre-commit and make it fix a single typo
  .codespellrc
  .pre-commit-config.yaml
  src/inventory/fields.rs
Labels: CI

#131 Retemplate lints configuration
  Cargo.toml
Labels: lints

#133 Set `--jobs` default to `min(20, CPU cores)`
  CHANGELOG.md
  README.md
  src/main.rs
Labels: CLI

#138 Document release process
  .pre-commit-config.yaml
  doc/releasing.md
Labels: documentation

#144 Document relation between `--trace-progress` and `-l TRACE`
  README.md
Labels: documentation
